export const ar = {
    // General
    appTitle: 'تـورلايز',
    appSubtitle: 'محلل المشاعر السياحية الذكي',
    adminUser: 'Admin User',
    logout: 'تسجيل الخروج',
    needHelp: 'هل تحتاج مساعدة؟',
    contactSupport: 'اتصل بالدعم',
    copyright: 'هذه المنصة تقدم تحليلات ذكية للمراجعات السياحية العربية وتدعم رؤية السعودية 2030.',

    // Sidebar
    dashboard: 'لوحة التحكم',
    newAnalysis: 'تحليل جديد',
    reports: 'التقارير',
    about: 'عن المشروع',

    // Login
    welcomeBack: 'مرحباً بعودتك',
    loginSubtitle: 'سجّل دخولك للوصول إلى لوحة تحليل المشاعر السياحية',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    loginButton: 'تسجيل الدخول',
    noAccount: 'ليس لديك حساب؟',
    createAccount: 'إنشاء حساب',

    // Signup
    createAccountTitle: 'إنشاء حساب جديد',
    createAccountSubtitle: 'ابدأ في تحليل بيانات المراجعات السياحية',
    fullName: 'الاسم الكامل',
    userType: 'نوع المستخدم',
    user: 'مستخدم',
    admin: 'مشرف',
    haveAccount: 'لديك حساب؟',
    login: 'تسجيل الدخول',
    createAccountButton: 'إنشاء الحساب',

    // City Input
    analyzeReviews: 'تحليل المراجعات السياحية',
    analyzeSubtitle: 'اختر مدينة سعودية، ودع الذكاء الاصطناعي يكشف لك عن انطباعات الزوار وتحليل مشاعرهم بدقة.',
    cityName: 'اسم المدينة',
    cityPlaceholder: 'مثال: العلا، الرياض، جدة...',
    discoverMessage: '✨ اكتشف ما يقوله الزوار عن وجهتك المفضلة',
    analyzeMessage: 'نحلل آلاف المراجعات من Google Maps و X لنقدم لك رؤية شاملة ودقيقة عن تجارب السياح في المدن السعودية',
    startAnalysis: 'بدء التحليل',

    // Dashboard
    noData: 'لا توجد بيانات حالياً',
    startNewAnalysis: 'بدء تحليل جديد',
    analysisResults: 'نتائج تحليل',
    lastUpdate: 'آخر تحديث',
    createPDF: 'إنشاء تقرير PDF',
    totalReviews: 'إجمالي المراجعات',
    positive: 'إيجابية',
    negative: 'سلبية',
    neutral: 'محايدة',
    sentimentDistribution: 'توزيع المشاعر',
    wordCloud: 'الكلمات الأكثر تكراراً (Word Cloud)',
    topTopics: 'أهم المواضيع',
    reviewDetails: 'تفاصيل المراجعات',
    filterAll: 'الكل',
    filterPositive: 'إيجابي',
    filterNegative: 'سلبي',
    filterNeutral: 'محايد',

    // Chart
    positiveLabel: 'إيجابي',
    neutralLabel: 'محايد',
    negativeLabel: 'سلبي',

    // Other
    frequency: 'تكرار',

    // Report
    noReportData: 'لا توجد بيانات للتقرير',
    mustAnalyzeFirst: 'يجب عليك إجراء تحليل أولاً قبل إنشاء التقرير',
    backToDashboard: 'العودة للوحة التحكم',
    downloadReport: 'تحميل التقرير (PDF)',
    reportTitle: 'تقرير تحليل المشاعر السياحية',
    analysisSummary: 'ملخص التحليل',
    reviews: 'المراجعات',
    keywords: 'الكلمات المفتاحية',
    sampleReviews: 'نماذج من المراجعات',
    autoGenerated: 'تم إنشاء هذا التقرير تلقائياً بواسطة نظام محلل المشاعر السياحية الذكي.',

    // About
    aboutDescription: 'منصة ذكية لتحليل المشاعر السياحية العربية باستخدام الذكاء الاصطناعي ( API)، وتقدم تقارير تدعم تحسين جودة الخدمات في قطاع السياحة السعودي بما يتماشى مع رؤية 2030.',
    problemTitle: 'المشكلة',
    problemDesc: 'صعوبة تحليل آلاف المراجعات النصية يدوياً واستخلاص رؤى دقيقة لصناع القرار.',
    solutionTitle: 'الحل',
    solutionDesc: 'نظام آلي يعالج النصوص العربية، يصنف المشاعر، ويستخرج الكلمات المفتاحية لحظياً.',
    goalTitle: 'الهدف',
    goalDesc: 'تحسين التجربة السياحية في المملكة من خلال فهم صوت الزائر.',
    supervisorTitle: 'مشرف المشروع',
    supervisorName: 'د. مفرح القحطاني',
    supervisorRole: 'مشرف المشروع',
    teamTitle: 'فريق العمل',
    teamMember: 'عضو الفريق',
};
