export const en = {
    // General
    appTitle: 'Tourism Sentiment Analyzer',
    appSubtitle: 'Smart Tourism Sentiment Analyzer',
    adminUser: 'Admin User',
    logout: 'Logout',
    needHelp: 'Need Help?',
    contactSupport: 'Contact Support',
    copyright: 'This platform provides smart analytics for Arabic tourism reviews and supports Saudi Vision 2030.',

    // Sidebar
    dashboard: 'Dashboard',
    newAnalysis: 'New Analysis',
    reports: 'Reports',
    about: 'About',

    // Login
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Log in to access the Tourism Sentiment Analysis Dashboard',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    loginButton: 'Login',
    noAccount: 'Don\'t have an account?',
    createAccount: 'Create Account',

    // Signup
    createAccountTitle: 'Create New Account',
    createAccountSubtitle: 'Start analyzing tourism review data',
    fullName: 'Full Name',
    userType: 'User Type',
    user: 'User',
    admin: 'Admin',
    haveAccount: 'Have an account?',
    login: 'Login',
    createAccountButton: 'Create Account',

    // City Input
    analyzeReviews: 'Tourism Reviews Analysis',
    analyzeSubtitle: 'Choose a Saudi city, and let AI reveal visitor impressions and sentiment analysis accurately.',
    cityName: 'City Name',
    cityPlaceholder: 'Example: AlUla, Riyadh, Jeddah...',
    discoverMessage: '✨ Discover what visitors say about your favorite destination',
    analyzeMessage: 'We analyze thousands of reviews from Google Maps and X to provide you with a comprehensive and accurate view of tourist experiences in Saudi cities.',
    startAnalysis: 'Start Analysis',

    // Dashboard
    noData: 'No data currently available',
    startNewAnalysis: 'Start New Analysis',
    analysisResults: 'Analysis Results',
    lastUpdate: 'Last Update',
    createPDF: 'Generate PDF Report',
    totalReviews: 'Total Reviews',
    positive: 'Positive',
    negative: 'Negative',
    neutral: 'Neutral',
    sentimentDistribution: 'Sentiment Distribution',
    wordCloud: 'Most Frequent Words (Word Cloud)',
    topTopics: 'Top Topics',
    reviewDetails: 'Review Details',
    filterAll: 'All',
    filterPositive: 'Positive',
    filterNegative: 'Negative',
    filterNeutral: 'Neutral',

    // Chart
    positiveLabel: 'Positive',
    neutralLabel: 'Neutral',
    negativeLabel: 'Negative',

    // Other
    frequency: 'Frequency',

    // Report
    noReportData: 'No Data for Report',
    mustAnalyzeFirst: 'You must run an analysis first before generating the report',
    backToDashboard: 'Back to Dashboard',
    downloadReport: 'Download Report (PDF)',
    reportTitle: 'Tourism Sentiment Analysis Report',
    analysisSummary: 'Analysis Summary',
    reviews: 'Reviews',
    keywords: 'Keywords',
    sampleReviews: 'Sample Reviews',
    autoGenerated: 'This report was automatically generated by the Smart Tourism Sentiment Analyzer system.',

    // About
    aboutDescription: 'A smart platform for analyzing Arabic tourism sentiment using AI (API), providing reports that support improving service quality in the Saudi tourism sector in line with Vision 2030.',
    problemTitle: 'The Problem',
    problemDesc: 'Difficulty in manually analyzing thousands of text reviews and extracting accurate insights for decision-makers.',
    solutionTitle: 'The Solution',
    solutionDesc: 'An automated system that processes Arabic text, classifies sentiment, and extracts keywords instantly.',
    goalTitle: 'The Goal',
    goalDesc: 'Improving the tourism experience in the Kingdom by understanding the visitor\'s voice.',
    supervisorTitle: 'Project Supervisor',
    supervisorName: 'Dr. Mufarreh Al-Qahtani',
    supervisorRole: 'Project Supervisor',
    teamTitle: 'The Team',
    teamMember: 'Team Member',
};
