/**
 * Global Type Definitions (types.ts)
 * 
 * Centralized TypeScript type dictionary establishing the schema contracts for the entire frontend application.
 * Enforces strict structural typing to eliminate runtime errors across components, contextual managers, and API services.
 */

/**
 * Enumeration mapping the core classification outputs generated by the hugging face ML Model (CAMeLBERT).
 * Categorizes extracted raw text into three distinct emotional polarities.
 */
export enum Sentiment {
    POSITIVE = 'Positive',
    NEGATIVE = 'Negative',
    NEUTRAL = 'Neutral'
}

/**
 * Interface defining the exact geometric structure of an individual scraped review.
 * Passed between the backend API and localized frontend render components (e.g., ReviewItem.tsx).
 */
export interface Review {
    id: string; // Unique identifier (typically a UUID generated post-scraping)
    text: string; // The literal raw content extracted from the data source
    sentiment: Sentiment; // ML-evaluated categorical prediction
    source: string; // Target origin platform string representation (e.g., 'GoogleMaps')
    date: string; // Chronological marker of review submission parsed into a readable string
    author: string; // Masked or explicit textual identity of the reviewer
}

/**
 * Interface modeling the primary Account authorization architecture.
 * Determines hierarchy constraints via role-based access control (RBAC).
 */
export interface User {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    password: string; // Local state transient storage only (do not serialize or pass to external unencrypted APIs)
    role: 'user' | 'admin'; // Authorization level (limits accessibility across UI structures)
}

/**
 * Structurally encapsulates aggregated numerical metrics regarding a specific target entity (City).
 * Utilized dynamically by Rechart UI layers indicating proportion and volume.
 */
export interface AnalysisStats {
    totalReviews: number; // Aggregate sum mapping total scraped elements
    positiveCount: number; // Volume of positively correlated outputs
    negativeCount: number; // Volume of negatively correlated outputs
    neutralCount: number; // Volume of indifferent/factual outputs
    averageRating: number; // Standardized continuous scalar representation ranging [1.0 - 5.0]
}

/**
 * Word Frequency mapping matrix element.
 * Binds literal textual string extractions to their calculated qualitative mass.
 * Exclusively consumed by the D3.js WordCloud engine for SVG topological layouts.
 */
export interface WordFreq {
    text: string;
    value: number; // Occurrences/weight metric adjusting D3 scale coordinates
}

/**
 * Grand aggregator interface representing a complete Sentiment Report entity schema.
 * Bonds spatial geography identities with mapped AI insights and literal scraped matrices.
 */
export interface CityAnalysisData {
    cityName: string; // Target spatial geography explicitly queried by the end-user
    stats: AnalysisStats; // Quantitative snapshot summary
    reviews: Review[]; // Detailed historical listing for transparency and empirical justification
    topWords: WordFreq[]; // Calculated NLP topological extraction matrix mapping trending concepts
    timestamp: string; // Traceability marker signaling when the ML pipeline achieved execution
}
